name: Close Discussions

on:
  pull_request:
    types: [closed]

jobs:
  close-discussion:
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR is merged
      if: github.event.pull_request.merged == true
      run: echo "PR is merged"

    - name: Extract Discussion IDs and Keywords
      id: get-discussion-info
      run: |
        keywords="close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved"
        pr_body="${{ github.event.pull_request.body }}"
        discussion_ids=()
        while IFS= read -r line; do
          for keyword in $keywords; do
            if [[ "$line" =~ $keyword\ #([0-9]+) ]]; then
              discussion_ids+=(${BASH_REMATCH[1]})
            fi
          done
        done <<< "$pr_body"
        echo "discussion-ids=${discussion_ids[@]}" >> $GITHUB_ENV

    - name: Close discussions
      if: github.event.pull_request.merged == true && env.discussion-ids != ""
      run: |
        for discussion_id in ${{ env.discussion-ids }}; do
          echo "Closing discussion #$discussion_id"
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/discussions/$discussion_id \
            -d '{"state":"closed"}'
        done
